# Generated by Django 3.0.7 on 2020-06-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartinfo',
            options={'verbose_name': '购物车商品信息', 'verbose_name_plural': '购物车商品信息'},
        ),
    ]
